# Generated by Django 2.2.6 on 2019-10-11 06:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostTitle', models.CharField(max_length=200)),
                ('PostMessage', models.TextField(blank=True)),
                ('Image', models.ImageField(upload_to='photos')),
                ('Catagory', models.CharField(max_length=200)),
                ('DateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
