# Generated by Django 2.2.6 on 2019-10-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feeds',
        ),
    ]
